remote_theme: pages-themes/cayman@v0.2.0
plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Project Portfolio"
description: Data Visualization, Analytics & Modelling | Business Intelligence | Python | SQL
nav:
  - title: Home
    url: /
  - title: Contact
    url: /contact/
<a href= https://builtbyg.github.io/contact>"Contact"</a>

