title: Portfolio
description: Data Modelling and Visualization | Business Intelligence | Python
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
remote_theme: tuur29/pages-themes-cayman
plugins:
  - jekyll-remote-theme
nav:
  - title: Home
    url: https://builtbyg.github.io/
  - title: Contact
    url: https://builtbyg.github.io/contact/


